KUBERNETES_PROVIDER = "aws"
KUBE_AWS_ZONE = "eu-central-1b"
NUM_MINIONS = 3
MINION_SIZE = "t2.medium"
MASTER_SIZE = "t2.medium"
AWS_S3_REGION = "eu-central-1"
INSTANCE_PREFIX = "k8s"
AWS_S3_BUCKET = "kh-kube-artifacts"
MINION_ROOT_DISK_SIZE = 20
MASTER_ROOT_DISK_SIZE = 12
KUBE_DIST = "/home/khattab/kubernetes-1.1.2"
BDP_CONFIG_DIR = "/home/khattab/BDP"

[ambari]
AMBARI_NODES = 4
AMBARI_BLUEPRINT = "ha-hdfs"
AMBARI_BLUEPRINT_URL = "https://goo.gl/GRVbkp"

[rabbitmq]
RABBITMQ_NODES = 3

[cassandra]
CASSANDRA_NODES = 3

[kafka]
KAFKA_NODES = 2

[spark]
SPARK_WORKERS = 5
