KUBERNETES_PROVIDER: aws
KUBE_AWS_ZONE: eu-central-1b
NUM_MINIONS: 3
MINION_SIZE: t2.medium
MASTER_SIZE: t2.medium
AWS_S3_REGION: eu-central-1
INSTANCE_PREFIX: k8s
AWS_S3_BUCKET: kh-kube-artifacts
MINION_ROOT_DISK_SIZE: 20
MASTER_ROOT_DISK_SIZE: 12

AMBARI_NODES:  5
RABBITMQ_NODES: 3
CASSANDRA_NODES: 3
KAFKA_NODES: 2
SPARK_WORKERS: 5
KUBE_DIST: /home/khattab/kubernetes-1.1.2
BDP_CONFIG_DIR: /home/khattab/BDP
AMBARI_BLUEPRINT: ha-hdfs
AMBARI_BLUEPRINT_URL: https://goo.gl/GRVbkp
